### ISSUE TITLE
main.py instantly closes after opening

### ISSUE THREAD

**Issue by bvnnyy** [Nyx-177/Twitch-Account-Creator#22]
installed reqs etc updated python still closes

**Comment by bvnnyy** [comment]
C:\Users\becky\Downloads\Twitch-Account-Creator-main (1)\Twitch-Account-Creator-main\main.py:26: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
  profile = webdriver.FirefoxProfile()

now i get that

**Comment by bvnnyy** [comment]
> The deprecation warning is not an issue, the program uses a version of selenium where it still works

Which version?

**Comment by Nyx-177** [comment]
The version in the requirements.txt file, if you followed the installation instructions you should have the correct version
